name: Check Tests

on:
  pull_request:
    branches: [gcloud, production, dev] # specify the branch you want the deploy to take place from
  # push:
  #   branches: [gcloud, production]

env:
  ENV_FILE: ${{ secrets.ENV_FILE }} # Secret with all additional environment variables.
  REACT_ENV_FILE: ${{ secrets.REACT_ENV_FILE }}

jobs:
  server-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: crm_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Add Server .env file #making 2 files until we figure out the file scope issue
        run: |
          echo "$ENV_FILE" > .env
          mv .env ./src/.env
          echo "$ENV_FILE" > .env
        working-directory: ./server
      - name: Install Server dependencies
        run: npm i
        working-directory: ./server
      - name: migrate and check seeders
        run: npm run testseeders
      - name: run tests
        run: npm run test
        env:
          MYSQL_DATABASE_TEST: crm_test
          MYSQL_PASSWORD: null
        working-directory: ./server

  client-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Client .env file
        run: echo "$REACT_ENV_FILE" > .env
        working-directory: ./client
      - name: Install Client dependencies
        run: npm i
        working-directory: ./client
      - name: Run Client
        run: npm start & npx wait-on http://localhost:3000
        working-directory: ./client
      - name: Run Client Tests
        run: npx cypress run
        working-directory: ./client
